sudo: required
language: generic

services:
  - docker

script:
  - echo "Run test..."

after_success:
  - docker build -t pozzallo/frontend ./frontend
  - docker build -t pozzallo/mysql ./mysql
  - docker build -t pozzallo/resource ./recipe-book
  - docker build -t pozzallo/zuul ./recipe-book-ui

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pozzallo/frontend
  - docker push pozzallo/mysql
  - docker push pozzallo/resource
  - docker push pozzallo/zuul